# name: Deploy

# on:
#   push:
#     branches: [master]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 拉代码
#         uses: actions/checkout@v2

#       - name: 安装依赖 & 构建
#         run: |
#           npm install
#           npm run build

#       - name: 拷贝构建产物到服务器
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: root
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           source: 'dist/*'
#           target: '/workspace/dist'

#       - name: 重启 Nginx
#         uses: appleboy/ssh-action@v0.1.6
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: root
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             systemctl restart nginx
name: Auto Deploy on Push

on:
  push:
    branches: [main] # 监听 main 分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取仓库
        uses: actions/checkout@v3

      - name: 构建项目（可选：如需预处理）
        run: |
          npm install
          npm run build

      - name: 使用 scp 上传到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/workspace/dist"
